# -*- coding: utf-8 -*-
"""OZL16000222_KEREM_ARIKÇILI_DB_HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iGz8On3mEr44ZyWTMWXmHBlrP8FCE3cx
"""

"""READ FILE PART"""
"""OZL16000222-KEREM-ARIKÇILI"""


import pandas as pd

citiesDataFrame = pd.read_csv("C:/Users/kerem/Desktop/homework2/cities.csv")
 
"""df.head(5)"""
citiesDataFrame

citiesDataFrame.head(10)

"""INSERT PART"""
listOfSeries = [pd.Series([41, 2, 52, '"N"',120,30,32,'"W"','"Nagazaki"','PA'], index=citiesDataFrame.columns ) ,
                pd.Series([43,2,50,'"W"',110,25,30,'"W"','"Hiroşima"','PB'], index=citiesDataFrame.columns ) ,
                pd.Series([40,17,48,'"W"',100,20,29,'"N"','"Fukuoka"','PD'], index=citiesDataFrame.columns ) 
                ]


modOfObj=citiesDataFrame.append(listOfSeries,ignore_index=True)
citiesDataFrame=modOfObj

 

citiesDataFrame

"""UPDATE PART"""
citiesDataFrame.loc[citiesDataFrame['LatD'] == 41, ' "LatM"'] = 65
citiesDataFrame.loc[citiesDataFrame['LatD'] == 42, ' "City"'] = 'Kansai'
citiesDataFrame.loc[citiesDataFrame['LatD'] == 40, ' "City"'] = 'Kyoto'
citiesDataFrame

citiesDataFrame.loc[citiesDataFrame[' "LatM"']<5]

citiesDataFrame.loc[(citiesDataFrame[' "LatM"']<20) & (citiesDataFrame[' "EW"']==' "W"')]

"""DROP PART"""
citiesDataFrame.drop('LatD',axis=1)

citiesDataFrame.drop([1])

citiesDataFrame.drop(citiesDataFrame.index[0:100])